UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'South America' WHERE (`ID` = '1');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Oceania' WHERE (`ID` = '2');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '3');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'South America' WHERE (`ID` = '4');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '5');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'United Kingdom' WHERE (`ID` = '6');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '7');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '8');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '9');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '10');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '11');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '12');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'Europe' WHERE (`ID` = '13');
UPDATE `Tennis_Competition`.`Countries` SET `Region` = 'North America' WHERE (`ID` = '14');