version: "3.9"  # optional since v1.27.0
services:
  mariadb:
    image: mariadb
    ports:
      - "3308:3306"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root